sudo: false
language: node_js
cache:
    directories:
        - elm-stuff
install:
    - npm install elm
    - elm package install --yes
script:
    - make
deploy:
    provider: s3
    access_key_id:
        - secure: "BjnIdvza9nN3s/UiCZQhVqoUus7Tx0WTMfXgd/pRUHNHzR4TLE3bVgMjIOouiZI9UEAkrI0T4lOVQPOrFYzosO7GqrsID/kLP/boblUMIdSk4S3PswBbR3sjpZaoxdYnkCH28QJ+o4r5UYHiaoBQaYSKdSQUIYWeiZzSWj+58Gg4AAUfDVzQvH6ZC/zZkgh4bWe+QVCC8lpeGSOzWh2qDlGzK42yVBDgbh8K6tWm153558UAwtkZarfKbcRKoZ7DGm/MATYIeYuLZlBGMjWBBlypujcWZu5wcar2uI0IGfslusdfxt+tPTebLIDOj0VeCvgGY02r/MhiKBib39IVb13rfQh0SJB/2dPXHVQ2c4PhDIGSxUDgd4oNXojg8Gncebo08RMtQgHAhO2NdCEpm00NxIkAtC2dSAbO2J7gl3juHqvg+W0bGdi0NLdMueUuJO8Ubpjp8CzhacBEGc9mrk0X14l/gQM0a4caPBaxZ1nWqVLgiU50XYOAR691ee4WQ74EyT4g0aNbmx2ALFnWfHF66IiByQXXE7Zxz/aXCcw/BqlPJ2QqOExssR6y2VQ/F3Vi0jp8YFLheFa0CrZhDXtSazFfbMpmS14qxeoWQbLMeXRZroOfQ0lqevwcaj26bCfTjHvUAcuCZcgyv24uu3BnqS/nNdHefb3R8h2RIZI="
    secret_access_key:
        - secure: "GJ9vnl5pA4ku9dBM9OZ8lntf193ko3M10e589pdGmODZNVEeeWrkCmyEAJ87Zk5p8NVIvs2pvUXXZpvbK0C2VBZizeR01HfkQLnNX8h222seUqDlUkNTOjk2DQGCzSQtODoZ1iQa9MjAeJvvYt7F3W/Aa6ewNbmAk56T7xKSxr4+AhbnWLWE/3t4lLb/y241Ft1AeXbF88alTNUUqLzG22nL7xiU+trM1WSdhEpXCbY5HZQQU8jjd+iZ0RTLatyUT9wICTgnxRcVvNoTxiU+TVKteGdzKXTjCWdRgIUcYlohdu8HgzBehd1W0YUgPbyRUMNdUB4bClhcWszUeQIXLTbVMT/SzYefwvPObNdBB+HXszMhVRhSWWn1lmW8Qb7Et62Ed6gmH8jwhKL0JJiZ7fDtz4FTd6hU75JSG+eCF38wJNvpNpcOwvJ9RT/7BaaikBGGLTNQ8+gMwMYoJN/DfUp4VjUGyfFwj+aXKb9dZAvJuUgnxg4W9LRiJoSzT9l9W1R+iA0JhC8szw5LjZoeJZ8gSSFyrfPuOd4x2Od0azLZb+pz/NDDg2XTp5nYlr3untAQNjcJ2BKPiVwTagiFvXaZsqXQI0ipqgodqTGIoRZ5TyOdV51LKy7ypr2ntYjcTxiSgNh+9FKPSNHhmwHPlc+yP6T5MjE/v7atqelSsv4="
    bucket: "archiv.ohlasy.info"
    skip_cleanup: true
    local_dir: build
    acl: public_read
